name: cache_manager
description: "A new Flutter project."
version: 1.0.0
homepage: https://github.com/CoderNamedHendrick/cache_manager
repository: https://github.com/CoderNamedHendrick/cache_manager
issue_tracker: https://github.com/CoderNamedHendrick/cache_manager/issues

environment:
  sdk: ^3.0.0

dependencies:
  hive: ^2.2.3

dev_dependencies:
  lints: any
  test: ^1.25.15
