name: cache_manager_plus
description: "A Dart package for managing cache with support for multiple storage backends."
version: 1.0.1
homepage: https://github.com/CoderNamedHendrick/cache_manager
repository: https://github.com/CoderNamedHendrick/cache_manager
issue_tracker: https://github.com/CoderNamedHendrick/cache_manager/issues

topics:
  - caching
  - cache
  - backend
  - cache-management
  - data-management

environment:
  sdk: ^3.0.0

dependencies:

dev_dependencies:
  lints: any
  test: ^1.25.15
