name: cache_manager
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.0.0

dependencies:
  hive: ^2.2.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
