name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests-and-upload-coverage-report:
    name: Test package
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: 3.29.3
          channel: 'stable'

      - name: Install dependencies
        run: dart pub get

      - run: dart pub global activate coverage
        name: Activate dart coverage

      - name: Format code
        run: dart format . --set-exit-if-changed

      - name: Lint analysis
        run: dart analyze

      - name: Run tests
        run: dart pub global run coverage:test_with_coverage

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}